### ISSUE TITLE
Doesn't work with IME

### ISSUE THREAD

**Issue by dimaqq** [seawind543/react-token-input#1] opened 2019-03-18 05:26 UTC
For example, when keyboard is set to Japanese:

<img width="338" alt="Screenshot 2019-03-18 at 14 25 51" src="https://user-images.githubusercontent.com/662249/54508616-c1a9f900-4989-11e9-8176-8cc51bcf1f9d.png">

In the example above, "Hiragana" is doubled.

Env: macOs, Chrome, Japanese keyboard input

**Comment by dimaqq** [comment] 2019-03-18 05:51
![kanji](https://user-images.githubusercontent.com/662249/54509428-dc31a180-498c-11e9-903d-775b85778d1e.gif)

Perhaps the video shows this better:
* type "kanji", select the characters, press enter — one token is displayed
* start typing, "k" and suddenly the new input shows (last token + k)
* finish typing, select characters, press enter — 2nd token == 1st token + new text
* more typing, select characters, press enter — 3rd token == 1st token + 2nd token + new text

**Comment by seawind543** [comment] 2021-08-10 17:49
Hi @dimaqq, 

Thank you for report this bug. Apologies for the late response. I need to find a device to help recreate the issue. 
I had made my investigation and plan to provide a solution soon.

### Root cause
- TokenInput detect the `keyDownEvent.key === Enter` case to grab the input-box value

- The keyDown behavior with `IME` of `Chrome` is different between `Mac` and `Windows`.
On the other hand, the behavior of Firefox is consistent in both of them.

- The `Enter` when typing with IME somehow should be considered as `select a text from the candidate list of IME` not be treated as to make an `enter` on the input-box. This makes sense the keyDownEvent.key returns `Process`.
However, the end-user does press the Enter key, and that also makes sense the keyDownEvent.key returns `Enter`.

So, I will say both Firefox and Chrome in Mac are correct (From different points of view).


### Proposed solution

- Not only check `keyDownEvent.key === Enter` but also check `keyDownEvent.keyCode !== 229`

---

### Mac

- With Chrome:

Typing (inputting): `abc Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "13" 
> code: "undefined" 

Typing (inputting): `漢字 Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "229" 
> code: "undefined" 

- With Firefox:

Typing (inputting): `abc Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "13" 
> code: "undefined" 

Typing (inputting): `漢字 Enter`
> [keyDownEvent] 
> key: "Process"
> keyCode: "229" 
> code: "undefined" 

- With Safari:

Typing (inputting): `abc Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "13" 
> code: "undefined" 

Typing (inputting): `漢字 Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "229" 
> code: "undefined" 

---
Windows

- With Chrome:

Typing (inputting): `abc Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "13" 
> code: "undefined" 

Typing (inputting): `漢字 Enter`
> [keyDownEvent] 
> key: "Process"
> keyCode: "229" 
> code: "undefined" 

- With Firefox:

Typing (inputting): `abc Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "13" 
> code: "undefined" 

Typing (inputting): `漢字 Enter`
> [keyDownEvent] 
> key: "Process"
> keyCode: "229" 
> code: "undefined" 

- With New Edge:

Typing (inputting): `abc Enter`
> [keyDownEvent] 
> key: "Enter"
> keyCode: "13" 
> code: "undefined" 

Typing (inputting): `漢字 Enter`
> [keyDownEvent] 
> key: "Process"
> keyCode: "229" 
> code: "undefined"

**Comment by seawind543** [comment] 2021-08-11 16:38
Chrome:  https://bugs.chromium.org/p/chromium/issues/detail?id=935275

**Comment by dimaqq** [comment] 2021-08-12 00:21
> Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=935275

👆🏿  that issue is for Chrome for Android. (noting it for future generations)

**Comment by dimaqq** [comment] 2021-08-12 00:27
OT: somehow https://seawind543.github.io/react-token-input/ did not get updated and still loads the old bundle version

**Comment by seawind543** [comment] 2021-08-13 13:38
Hi @dimaqq, 
The fix had been released with `v1.2.3`. And now you could try it on https://seawind543.github.io/react-token-input/

Feel free to let me know if any issues are found with the new version. Any suggestions for enhancement are also welcome, thank you.

**Closed** 2021-08-15 08:48 UTC
Labels: bug
